# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
_PBACTIVITYTYPE = descriptor.EnumDescriptor(
  name='PBActivityType',
  full_name='PBActivityType',
  filename='PBActivityType',
  values=[
    descriptor.EnumValueDescriptor(
      name='PARTY', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRAFFIC', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SHOPPING', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_PBACTIONTYPE = descriptor.EnumDescriptor(
  name='PBActionType',
  full_name='PBActionType',
  filename='PBActionType',
  values=[
    descriptor.EnumValueDescriptor(
      name='ACTIVITY', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SHARE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='JOIN', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_PBACTIONSTATUS = descriptor.EnumDescriptor(
  name='PBActionStatus',
  full_name='PBActionStatus',
  filename='PBActionStatus',
  values=[
    descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DELETED', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MARK', index=2, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_PBPROMOTIONSTATUS = descriptor.EnumDescriptor(
  name='PBPromotionStatus',
  full_name='PBPromotionStatus',
  filename='PBPromotionStatus',
  values=[
    descriptor.EnumValueDescriptor(
      name='RUNNING', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='END', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PENDDING', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_PBPAYTYPE = descriptor.EnumDescriptor(
  name='PBPayType',
  full_name='PBPayType',
  filename='PBPayType',
  values=[
    descriptor.EnumValueDescriptor(
      name='AA', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FREE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=10,
      options=None,
      type=None),
  ],
  options=None,
)


PARTY = 1
TRAFFIC = 2
SHOPPING = 3
ACTIVITY = 1
SHARE = 2
JOIN = 3
NORMAL = 1
DELETED = 2
MARK = 3
RUNNING = 0
END = 1
PENDDING = 2
AA = 1
FREE = 2
OTHER = 10



_PBALBUM = descriptor.Descriptor(
  name='PBAlbum',
  full_name='PBAlbum',
  filename='action.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='album_id', full_name='PBAlbum.album_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='PBAlbum.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='PBAlbum.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='image_list', full_name='PBAlbum.image_list', index=3,
      number=4, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBPROMOTION = descriptor.Descriptor(
  name='PBPromotion',
  full_name='PBPromotion',
  filename='action.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='promotion_id', full_name='PBPromotion.promotion_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start_date', full_name='PBPromotion.start_date', index=1,
      number=2, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end_date', full_name='PBPromotion.end_date', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='title', full_name='PBPromotion.title', index=3,
      number=4, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='PBPromotion.content', index=4,
      number=5, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='PBPromotion.status', index=5,
      number=6, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='merchant_id', full_name='PBPromotion.merchant_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBMERCHANT = descriptor.Descriptor(
  name='PBMerchant',
  full_name='PBMerchant',
  filename='action.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='merchant_id', full_name='PBMerchant.merchant_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='aibang_id', full_name='PBMerchant.aibang_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='PBMerchant.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='county', full_name='PBMerchant.county', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='addr', full_name='PBMerchant.addr', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tel', full_name='PBMerchant.tel', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cate', full_name='PBMerchant.cate', index=6,
      number=8, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rate', full_name='PBMerchant.rate', index=7,
      number=9, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cost', full_name='PBMerchant.cost', index=8,
      number=10, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='desc', full_name='PBMerchant.desc', index=9,
      number=11, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lng', full_name='PBMerchant.lng', index=10,
      number=12, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lat', full_name='PBMerchant.lat', index=11,
      number=13, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='work_time', full_name='PBMerchant.work_time', index=12,
      number=14, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='site_url', full_name='PBMerchant.site_url', index=13,
      number=15, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='web_url', full_name='PBMerchant.web_url', index=14,
      number=16, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wap_url', full_name='PBMerchant.wap_url', index=15,
      number=17, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='img_url', full_name='PBMerchant.img_url', index=16,
      number=18, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='promotions', full_name='PBMerchant.promotions', index=17,
      number=30, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='promotion_ids', full_name='PBMerchant.promotion_ids', index=18,
      number=31, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBACTIVITY = descriptor.Descriptor(
  name='PBActivity',
  full_name='PBActivity',
  filename='action.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='PBActivity.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='token', full_name='PBActivity.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='PBActivity.content', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='join_deadtime', full_name='PBActivity.join_deadtime', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hold_deadtime', full_name='PBActivity.hold_deadtime', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pay_type', full_name='PBActivity.pay_type', index=5,
      number=7, type=14, cpp_type=8, label=1,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='budget', full_name='PBActivity.budget', index=6,
      number=8, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='price', full_name='PBActivity.price', index=7,
      number=9, type=2, cpp_type=6, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='member_limit', full_name='PBActivity.member_limit', index=8,
      number=10, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='photo_list', full_name='PBActivity.photo_list', index=9,
      number=11, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='participants', full_name='PBActivity.participants', index=10,
      number=12, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='signups', full_name='PBActivity.signups', index=11,
      number=13, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment_count', full_name='PBActivity.comment_count', index=12,
      number=30, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='share_count', full_name='PBActivity.share_count', index=13,
      number=31, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='participant_count', full_name='PBActivity.participant_count', index=14,
      number=32, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mark_count', full_name='PBActivity.mark_count', index=15,
      number=33, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='merchant', full_name='PBActivity.merchant', index=16,
      number=50, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='location', full_name='PBActivity.location', index=17,
      number=51, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start_loc', full_name='PBActivity.start_loc', index=18,
      number=70, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end_loc', full_name='PBActivity.end_loc', index=19,
      number=71, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBACTION = descriptor.Descriptor(
  name='PBAction',
  full_name='PBAction',
  filename='action.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='action_id', full_name='PBAction.action_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='PBAction.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='c_date', full_name='PBAction.c_date', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='PBAction.user', index=3,
      number=4, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='activity', full_name='PBAction.activity', index=4,
      number=20, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment', full_name='PBAction.comment', index=5,
      number=21, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='related_action', full_name='PBAction.related_action', index=6,
      number=22, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PBCOMMENT = descriptor.Descriptor(
  name='PBComment',
  full_name='PBComment',
  filename='action.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='comment_id', full_name='PBComment.comment_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='PBComment.user', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='c_date', full_name='PBComment.c_date', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action_id', full_name='PBComment.action_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='PBComment.content', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='star', full_name='PBComment.star', index=5,
      number=6, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_reply', full_name='PBComment.is_reply', index=6,
      number=7, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reply_action_id', full_name='PBComment.reply_action_id', index=7,
      number=8, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='digest', full_name='PBComment.digest', index=8,
      number=9, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

import basic_pb2
import user_pb2

_PBALBUM.fields_by_name['user'].message_type = user_pb2._PBBRIEFUSER
_PBPROMOTION.fields_by_name['status'].enum_type = _PBPROMOTIONSTATUS
_PBMERCHANT.fields_by_name['promotions'].message_type = _PBPROMOTION
_PBACTIVITY.fields_by_name['type'].enum_type = _PBACTIVITYTYPE
_PBACTIVITY.fields_by_name['content'].message_type = basic_pb2._PBCONTACT
_PBACTIVITY.fields_by_name['pay_type'].enum_type = _PBPAYTYPE
_PBACTIVITY.fields_by_name['merchant'].message_type = _PBMERCHANT
_PBACTIVITY.fields_by_name['location'].message_type = basic_pb2._PBLOCATION
_PBACTIVITY.fields_by_name['start_loc'].message_type = basic_pb2._PBLOCATION
_PBACTIVITY.fields_by_name['end_loc'].message_type = basic_pb2._PBLOCATION
_PBACTION.fields_by_name['type'].enum_type = _PBACTIONTYPE
_PBACTION.fields_by_name['user'].message_type = user_pb2._PBBRIEFUSER
_PBACTION.fields_by_name['activity'].message_type = _PBACTIVITY
_PBACTION.fields_by_name['related_action'].message_type = _PBACTION
_PBCOMMENT.fields_by_name['user'].message_type = user_pb2._PBBRIEFUSER

class PBAlbum(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBALBUM

class PBPromotion(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBPROMOTION

class PBMerchant(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBMERCHANT

class PBActivity(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBACTIVITY

class PBAction(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBACTION

class PBComment(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBCOMMENT

